- id: '1600774245795'
  alias: 'Media Center: turn on'
  description: Turn on the mediacenter to the correct activity
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: playing
  condition:
  - condition: template
    value_template: '{{current_activity != harmony_activity}}'
  action:
  - service: remote.turn_on
    data:
      entity_id: '{{use_remote}}'
      activity: '{{harmony_activity}}'
  - delay:
      hours: 0
      minutes: 0
      seconds: 3
      milliseconds: 500
  - service: media_player.volume_set
    entity_id: media_player.living_room_tv
    data:
      entity_id: '{{player_id}}'
      volume_level: '{{player_volume}}'
  mode: single
  variables:
    use_remote: remote.harmonyjorik
    player_id: media_player.living_room_tv
    current_activity: '{{state_attr(use_remote, ''current_activity'')}}'
    content_type: '{{state_attr(player_id, "media_content_type")}}'
    state_mapping:
      movie:
        activity: Tv
      tvshow:
        activity: Tv
      music:
        activity: Stereo
        volume: 0.55
    state_map: '{{state_mapping[content_type] | default({})}}'
    harmony_activity: '{{state_map.activity | default(content_type)}}'
    player_volume: '{{state_map.volume | default(1.0)}}'
- id: '1600780656956'
  alias: 'Media Center: turn off'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    to: idle
    for: '30'
  condition: []
  action:
  - service: remote.turn_off
    entity_id: remote.harmonyjorik
    data: {}
  mode: single
- id: '1602060895444'
  alias: 'Backup: HA config'
  description: Backup the home assistant config files on sundays
  trigger:
  - platform: time
    at: 04:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: shell_command.git_commit
  - service: shell_command.git_push
  mode: single
- id: '1603394623458'
  alias: 'Lights Hall: Keep on'
  description: Keep the motion controlled light in the hallway on.
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'off'
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: '{{ states("input_number.hall_brightness") | int }}'
    entity_id: light.hall_light
  mode: single
- id: '1605718602600'
  alias: 'Vacuum: Clean Schedule'
  description: Every night clean the living room, dining room and kitchen
  trigger:
  - platform: time
    at: 06:00
  condition:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: docked
  - condition: template
    value_template: '{{not state_attr(''vacuum.xiaomi_vacuum_cleaner'', ''mop_attached'')}}'
  action:
  - service: xiaomi_miio.vacuum_clean_segment
    data:
      segments:
      - 19
      - 18
    target:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
- id: '1607868672746'
  alias: Goodnight
  description: Let's shutdown everything
  trigger:
  - platform: device
    type: turned_off
    device_id: 370a6454000711eb9cde01ebd6642b5a
    entity_id: light.tv_light
    domain: light
  condition:
  - condition: time
    after: '22:30'
    before: '6:00'
  action:
  - scene: scene.night
  mode: single
- id: '1608038614647'
  alias: Goodmorning
  description: Switch on relevant stuff
  trigger:
  - platform: time
    at: '6:45'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - scene: scene.day
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    above: '0'
  - service: input_number.set_value
    target:
      entity_id: input_number.hall_brightness
    data:
      value: 255
  mode: single
- id: '1608195471126'
  alias: 'Lights Hall: Brightness'
  description: Set the hall light brightness
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'on'
  - platform: state
    entity_id: input_number.hall_brightness
  condition:
  - condition: device
    type: is_on
    device_id: 3709d680000711ebbaace9167b0f017d
    entity_id: light.hall_light
    domain: light
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: light.tradfri_bulb_8
      above: input_number.hall_brightness
      attribute: brightness
    - condition: numeric_state
      below: input_number.hall_brightness
      attribute: brightness
      entity_id: light.tradfri_bulb_8
  action:
  - service: light.turn_on
    data:
      brightness: '{{states("input_number.hall_brightness") | int }}'
    entity_id: light.tradfri_bulb_8
  mode: single
- id: '1608561879306'
  alias: 'Lights Livingroom: Turn on (home)'
  description: ''
  trigger:
  - platform: state
    entity_id: light.hall_light
    from: 'off'
    to: 'on'
    id: HallLightOn
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  - condition: time
    after: '12:00'
  - condition: state
    entity_id: light.livingroom_lights
    state: 'off'
  - condition: state
    entity_id: group.humans
    state: not_home
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    entity_id: light.livingroom_lights
  - service: notify.notify_jorik
    data:
      message: Turned on the lights because you're now home!
  mode: single
- id: '1608806095722'
  alias: 'Lights Livingroom:  dim light'
  description: ''
  use_blueprint:
    path: lights/light_dimming.yaml
    input:
      end_percentage: '15'
      start_percentage: '100'
      dim_start_time: '20:30:00'
      dim_end_time: '22:00:00'
      output_light: light.livingroom_lights
      start_brightness: 255
      end_brightness: 70
- id: '1609102126486'
  alias: 'Lights hall: Sun under'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: numeric_state
    entity_id: input_number.hall_brightness
    above: '77'
  action:
  - service: input_number.set_value
    data:
      value: 77
    target:
      entity_id: input_number.hall_brightness
  mode: single
- id: '1609102178138'
  alias: 'Lights hall: Sun up'
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: input_number.hall_brightness
    below: '255'
  action:
  - service: input_number.set_value
    data:
      value: 255
    target:
      entity_id: input_number.hall_brightness
  mode: single
- id: '1612192541242'
  alias: 'Lights Livingroom: Turn on (sun)'
  description: Turn on the livingroom lights if the sun goes under
  use_blueprint:
    path: lights/light_enable_sun.yaml
    input:
      duration_min: 50
      elevation_offset: '10'
      output_light: light.livingroom_lights
      end_brightness: '255'
      start_brightness: '38'
      home_group: group.humans
- id: '1622458308421'
  alias: 'Https: Refresh'
  description: ''
  trigger:
  - platform: time
    at: '12:00'
  condition:
  - condition: template
    value_template: '{{now().day == 1}}'
  action:
  - service: shell_command.recrypt
  - service: notify.notify_jorik
    data:
      message: Restart HA within 30 days!
      title: Encryption refresh
  mode: single
- id: '1623509943578'
  alias: 'Plant: Moisture'
  description: Warn if the plant should be given water
  trigger:
  - platform: time
    at: '17:00'
  condition:
  - condition: numeric_state
    entity_id: sensor.ficux_lyrata_moisture
    below: '20'
  action:
  - service: notify.notify_jorik
    data:
      message: 'The plant should be given water! Moisture: {{states("sensor.ficux_lyrata_moisture")}}'
  mode: single
- id: '1624542421853'
  alias: 'Vacuum: Ensure docked'
  description: Ensure that the vacuum goes to the docking station
  trigger:
  - platform: time
    at: 06:30
  condition:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: error
  action:
  - service: vacuum.return_to_base
    target:
      entity_id: vacuum.xiaomi_vacuum_cleaner
  - delay:
      hours: 0
      minutes: 10
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: error
  - service: notify.notify_jorik
    data:
      title: Vacuum Not Docked
      message: The vacuum is still in error state!
  mode: single
- id: '1638808746106'
  alias: 'Lights Livingroom: Morning'
  description: ''
  trigger:
  - platform: state
    entity_id: light.livingroom_lights
    from: 'off'
    to: 'on'
  condition:
  - condition: time
    after: 06:00
    before: '11:00'
  action:
  - service: light.turn_on
    target:
      entity_id: light.livingroom_lights
    data:
      brightness: 255
      transition: 15
  mode: single
