- id: '1600351493180'
  alias: Dim Livingroom lights if on
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'on'
  action:
  - data:
      brightness_pct: 15
      transition: 5600
    entity_id: light.livingroom_lights
    service: light.turn_on
  - delay: '30'
  - data:
      brightness_pct: 15
      transition: 5600
    entity_id: light.livingroom_lights
    service: light.turn_on
  mode: single
- alias: Evening lights turn on (home)
  id: '1606467703020'
  description: "Turn the lights on because someone comes home"
  variables:
    begin_pct: 15
    end_pct: 100
    start_time: "20:00"
    end_time: "22:00"
    t_dim_start: "{{as_timestamp(now().date + ' ' + start_time)}}"
    t_dim_end: "{{as_timestamp(now().date + ' ' + end_time)}}"
    t_now: "{{as_timestamp(now())}}"
    enable_pct: >
       {% if t_now < t_dim_start %}
            begin_pct
        {% elif t_now > t_dim_end %}
            end_pct
        {% else %}
            {{begin_pct + (t_now - t_start) / (t_dim_end - t_dim_start) * (end_pct - begin_pct)}}
        {% endif %}
  trigger:
  - platform: state
    entity_id: group.humans
    to: home
  condition:
    condition: state
    entity_id: lights.livingroom_lights
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.livingroom_lights
    data:
        brightness_pct: '{{enable_pct}}'
- id: '1600679110748'
  alias: Evening lights turn on (sun)
  description: 'Turn the lights on because sun goes under'
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  condition:
  - condition: state
    entity_id: group.humans
    state: home
  - condition: time
    before: '20:00'
    after: '12:00'
  action:
  - service: light.turn_on
    entity_id: light.livingroom_lights
    data:
      brightness_pct: 15
  - delay: '1'
  - service: light.turn_on
    entity_id: light.livingroom_lights
    data:
      brightness_pct: 95
      transition: 1800
  mode: single
- id: '1600774245795'
  alias: Media center turn on
  mode: single
  description: Turn on the mediacenter to the correct activity
  variables:
    use_remote: remote.harmonyjorik
    player_id: media_player.living_room_tv
    content_type: '{{state_attr(player_id, "media_content_type")}}'
    video_states:
    - movie
    - tvshow
    music_states:
    - music
    activity_type: "{% if content_type in video_states %}\n    Tv\n{% elif content_type\
      \ in music_states %}\n   Stereo\n{% else %}\n    Unknown\n{% endif %}\n"
    volume_level: "{% if content_type in video_states %}\n   1.0\n{% elif content_type\
      \ in music_states %}\n   0.55\n{% else %}\n    0.0\n{% endif %}\n"
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: playing
  condition:
    condition: template
    value_template: '{{state_attr(use_remote, "current_activity") != activity_type}}'
  action:
  - service: remote.turn_on
    data:
      entity_id: '{{use_remote}}'
      activity: '{{activity_type}}'
  - delay:
      seconds: 3.0
  - service: media_player.volume_set
    entity_id: media_player.living_room_tv
    data:
      entity_id: '{{player_id}}'
      volume_level: '{{volume_level}}'
- id: '1600780656956'
  alias: Media center turn off
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  condition: []
  action:
  - service: remote.turn_off
    entity_id: remote.harmonyjorik
    data: {}
  mode: single
- id: '1602060895444'
  alias: weekly backup config
  description: Backup the home assistant config files on sundays
  trigger:
  - platform: time
    at: 04:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: shell_command.backup_git
    data: {}
  mode: single
- id: '1603394623458'
  alias: keep hall light on
  description: Keep the motion controlled light in the hallway on. Is automatically
    turned off at 00:00
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'off'
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'on'
  - platform: state
    entity_id: input_number.hall_brightness
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(input_number.hall_brightness) | int }}'
    entity_id: light.hall_light
  mode: single
- id: '1603458166556'
  alias: Turn off hall light
  description: ''
  trigger:
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'off'
    for: 00:00:20
  - platform: time
    at: 00:01
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.hall_light
  - service: automation.turn_off
    data: {}
    entity_id: automation.keep_hall_light_on
  mode: single
- id: '1605718602600'
  alias: Daily vacuuming
  description: Every night clean the living room, dining room and kitchen
  trigger:
  - platform: time
    at: '3:00'
  condition:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: docked
  action:
  - service: xiaomi_miio.vacuum_clean_segment
    data:
      segments:
      - 16
      - 17
      - 18
    entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
