- id: '1600679110748'
  alias: 'Lights Livingroom: Turn on (sun)'
  description: Turn the lights on because sun goes under
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'off'
  - condition: state
    entity_id: group.humans
    state: home
  - condition: time
    before: '20:00'
    after: '12:00'
  action:
  - service: light.turn_on
    entity_id: light.livingroom_lights
    data:
      brightness_pct: 15
  - delay: '1'
  - service: light.turn_on
    entity_id: light.livingroom_lights
    data:
      brightness_pct: 100
      transition: 1800
  mode: single
- id: '1600774245795'
  alias: 'Media Center: turn on'
  description: Turn on the mediacenter to the correct activity
  mode: single
  variables:
    use_remote: remote.harmonyjorik
    player_id: media_player.living_room_tv
    current_activity: '{{state_attr(use_remote, ''current_activity'')}}'
    content_type: '{{state_attr(player_id, "media_content_type")}}'
    state_mapping:
      movie:
        activity: Tv
      tvshow:
        activity: Tv
      music:
        activity: Stereo
        volume: 0.55
    state_map: '{{state_mapping[content_type] | default({})}}'
    harmony_activity: '{{state_map.activity | default(content_type)}}'
    player_volume: '{{state_map.volume | default(1.0)}}'
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: playing
  condition:
  - condition: template
    value_template: '{{current_activity != harmony_activity}}'
  action:
  - service: remote.turn_on
    data:
      entity_id: '{{use_remote}}'
      activity: '{{harmony_activity}}'
  - delay: '5.0'
  - service: media_player.volume_set
    entity_id: media_player.living_room_tv
    data:
      entity_id: '{{player_id}}'
      volume_level: '{{player_volume}}'
- id: '1600780656956'
  alias: 'Media Center: turn off'
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  - platform: state
    entity_id: media_player.living_room_tv
    to: idle
    for: '30'
  condition: []
  action:
  - service: remote.turn_off
    entity_id: remote.harmonyjorik
    data: {}
  mode: single
- id: '1602060895444'
  alias: 'Backup: HA config'
  description: Backup the home assistant config files on sundays
  trigger:
  - platform: time
    at: 04:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: shell_command.backup_git
    data: {}
  mode: single
- id: '1603394623458'
  alias: 'Lights Hall: Keep on'
  description: Keep the motion controlled light in the hallway on.
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'off'
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'on'
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states("input_number.hall_brightness") | int }}'
    entity_id: light.hall_light
  mode: single
- id: '1605718602600'
  alias: Vacuuming
  description: Every night clean the living room, dining room and kitchen
  trigger:
  - platform: time
    at: '3:00'
  condition:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: docked
  - condition: template
    value_template: '{{not state_attr(''vacuum.xiaomi_vacuum_cleaner'', ''mop_attached'')}}'
  action:
  - service: xiaomi_miio.vacuum_clean_segment
    data:
      segments:
      - 16
      - 17
      - 18
    entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
- id: '1607868672746'
  alias: Goodnight
  description: Let's shutdown everything
  trigger:
  - platform: device
    type: turned_off
    device_id: 370a6454000711eb9cde01ebd6642b5a
    entity_id: light.tv_light
    domain: light
  condition:
  - condition: time
    after: '22:30'
    before: '6:00'
  action:
  - scene: scene.night
  mode: single
- id: '1608038614647'
  alias: Goodmorning
  description: Switch on relevant stuff
  trigger:
  - platform: time
    at: '6:45'
  condition:
  - condition: state
    entity_id: input_boolean.vacation_mode
    state: 'off'
  action:
  - scene: scene.day
  mode: single
- id: '1608195471126'
  alias: 'Lights Hall: Brightness'
  description: Set the hall light brightness
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'on'
  - platform: state
    entity_id: input_number.hall_brightness
  condition:
  - condition: device
    type: is_on
    device_id: 3709d680000711ebbaace9167b0f017d
    entity_id: light.hall_light
    domain: light
  - condition: or
    conditions:
    - condition: numeric_state
      entity_id: light.hall_light
      value_template: '{{ (state_attr(''light.hall_light'', ''brightness'') / 255
        * 100) | round(0) }}'
      above: input_number.hall_brightness
    - condition: numeric_state
      entity_id: light.hall_light
      value_template: '{{ (state_attr(''light.hall_light'', ''brightness'') / 255
        * 100) | round(0) }}'
      below: input_number.hall_brightness
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states("input_number.hall_brightness") | int }}'
    entity_id: light.hall_light
  mode: single
- id: '1608561879306'
  alias: 'Lights Livingroom: Turn on (home)'
  description: ''
  trigger:
  - platform: state
    entity_id: group.humans
    to: home
  condition:
  - condition: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  - condition: time
    after: '12:00'
  - condition: state
    entity_id: light.livingroom_lights
    state: 'off'
  action:
  - service: light.turn_on
    data:
      brightness_pct: 100
    entity_id: light.livingroom_lights
  mode: single
- id: '1608806095722'
  alias: 'Lights: Livingroom (dimming) '
  description: ''
  use_blueprint:
    path: lights/light_dimming.yaml
    input:
      end_percentage: '15'
      start_percentage: '100'
      dim_start_time: '20:30:00'
      dim_end_time: '22:00:00'
      output_light: light.livingroom_lights
- id: '1609102126486'
  alias: 'Lights hall: Sun under'
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: numeric_state
    entity_id: input_number.hall_brightness
    above: '30'
  action:
  - service: input_number.set_value
    data:
      value: 30
    entity_id: input_number.hall_brightness
  mode: single
- id: '1609102178138'
  alias: 'Lights hall: Sun up'
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition:
  - condition: numeric_state
    entity_id: input_number.hall_brightness
    below: '100'
  action:
  - service: input_number.set_value
    data:
      value: 100
    entity_id: input_number.hall_brightness
  mode: single
