- id: '1600351493180'
  alias: Dim Livingroom lights if on
  description: ''
  trigger:
  - at: '20:00'
    platform: time
  condition:
  - condition: state
    entity_id: light.livingroom_lights
    state: 'on'
  action:
  - data:
      brightness_pct: 15
      transition: 5600
    entity_id: light.livingroom_lights
    service: light.turn_on
  - delay: '30'
  - data:
      brightness_pct: 15
      transition: 5600
    entity_id: light.livingroom_lights
    service: light.turn_on
  mode: single
- id: '1600679110748'
  alias: Evening lights turn on
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sun.sun
    attribute: elevation
    below: '10'
  condition:
  - condition: state
    entity_id: group.humans
    state: home
  action:
  - service: light.turn_on
    data:
      brightness_pct: 95
      transition: 1800
    entity_id: light.livingroom_lights
  mode: single
- id: '1600774245795'
  alias: Media center turn on
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: playing
  condition:
  - condition: template
    value_template: "{% if is_state_attr('media_player.living_room_tv', 'media_content_type',\
      \ \"movie\") -%}\n  {{not is_state_attr('remote.harmonyjorik', 'current_activity',\
      \ 'Tv')}}\n{%- else -%}\n  {{not is_state_attr('remote.harmonyjorik', 'current_activity',\
      \ 'Stereo')}}\n{%- endif %}"
  action:
  - service: remote.turn_on
    data:
      activity: "{% if state_attr('media_player.living_room_tv', 'media_content_type')\
        \ == 'movie' -%}\n  Tv\n{%- elif state_attr('media_player.living_room_tv',\
        \ 'media_content_type') == 'music' -%}\n  Stereo\n{%- endif %}"
    entity_id: remote.harmonyjorik
  - delay: '1.0'
  - wait_template: '{{ state_attr(''remote.harmonyjorik'', ''activity_starting'')
      == null }}'
    continue_on_timeout: true
    timeout: '5.0'
  - service: media_player.volume_set
    data:
      volume_level: "{% if state_attr('media_player.living_room_tv', 'media_content_type')\
        \ == 'movie' -%}\n  1.0\n{%- elif state_attr('media_player.living_room_tv',\
        \ 'media_content_type') == 'music' -%}\n  0.55\n{%- endif %}"
    entity_id: media_player.living_room_tv
  mode: single
- id: '1600780656956'
  alias: Media center turn off
  description: ''
  trigger:
  - platform: state
    entity_id: media_player.living_room_tv
    to: 'off'
  condition:
  - condition: template
    value_template: '{{ trigger.from_state != "unavailable" }}'
  action:
  - service: remote.turn_off
    data: {}
    entity_id: remote.harmonyjorik
  mode: single
- id: '1602060895444'
  alias: weekly backup config
  description: Backup the home assistant config files on sundays
  trigger:
  - platform: time
    at: 04:00
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - service: shell_command.backup_git
    data: {}
  mode: single
- id: '1603394623458'
  alias: keep hall light on
  description: Keep the motion controlled light in the hallway on. Is automatically
    turned off at 00:00
  trigger:
  - platform: state
    entity_id: light.hall_light
    to: 'off'
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'on'
  - platform: state
    entity_id: input_number.hall_brightness
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness_pct: '{{ states(''input_number.hall_brightness'') | int }}'
    entity_id: light.hall_light
  mode: single
- id: '1603458166556'
  alias: Turn off hall light
  description: ''
  trigger:
  - platform: state
    entity_id: automation.keep_hall_light_on
    to: 'off'
    for: 00:00:20
  - platform: time
    at: 00:01
  condition: []
  action:
  - service: light.turn_off
    data: {}
    entity_id: light.hall_light
  - service: automation.turn_off
    data: {}
    entity_id: automation.keep_hall_light_on
  mode: single
- id: '1605718602600'
  alias: Daily vacuuming
  description: Every night clean the living room, dining room and kitchen
  trigger:
  - platform: time
    at: '3:00'
  condition:
  - condition: state
    entity_id: vacuum.xiaomi_vacuum_cleaner
    state: docked
  action:
  - service: xiaomi_miio.vacuum_clean_segment
    data:
      segments:
      - 16
      - 17
      - 18
    entity_id: vacuum.xiaomi_vacuum_cleaner
  mode: single
