- platform: command_line
  name: CPU Temperature
  command: "cat /sys/class/thermal/thermal_zone0/temp"
  unit_of_measurement: "°C"
  value_template: "{{ value | multiply(0.001) | round(1) }}"
  
- platform: command_line
  name: GPU Temp
  command: "/opt/vc/bin/vcgencmd measure_temp"
  unit_of_measurement: "°C"
  value_template: '{{ value | regex_findall_index("=([0-9]*\.[0-9]*)", 0) }}'
  
- platform: systemmonitor
  resources:
    - type: processor_use
    - type: memory_use_percent