blueprint:
  name: Lights dimming
  description: Dim light(s) gradually between a start and end time.
  domain: automation
  
  input:
    # Brightness input
    start_brightness:
      name: Start Brightness.
      description: The start brighness.
      default: 255
      selector:
        number:
          min: 1
          max: 255
    end_brightness:
      name: End Brightness.
      description: The end brightness.
      default: 38
      selector:
        number:
          min: 1
          max: 255

    # Dim timing inputs          
    dim_start_time:
      name: Helper with the start time for dimming
      description: Select a time helper (input_datetime)
      default: input_datetime.dim_lights_start
      selector:
        entity:
          domain: input_datetime
          
    dim_end_time:
      name: Helper with the end time for dimming
      description: Select a time helper (input_datetime)
      default: input_datetime.dim_lights_end
      selector:
        entity:
          domain: input_datetime

    # Light to dim
    output_light:
      name: Output Light
      description: Light to turn on when coming home.
      selector:
        entity:
          domain: light

variables:
  start_entity: !input dim_start_time
  end_entity: !input dim_end_time
  brightness_start: !input start_brightness
  brightness_end: !input end_brightness
  morning_reset: "06:00:00"

  now_ts: "{{now().timestamp() | int}}"
  start_ts: "{{ today_at(states(start_entity)).timestamp() | int }}"
  end_ts: "{{ today_at(states(end_entity)).timestamp() | int}}"
  
  transition_time: "{{ [end_ts - start_ts, 1] | max | int }}"
  
  set_initial_brightness: "{{trigger is defined and trigger.platform == 'state'}}"
  initial_brightness: >
    {% if now_ts <= start_ts %}
      {{brightness_start}}
    {% elif now_ts >= end_ts %}
      {{brightness_end}}
    {% elif now_ts < today_at(morning_reset).timestamp() %}
      {{brightness_end}}
    {% else %}
      {{ brightness_end + (now_ts - start_ts) / (transition_time) * (brightness_start - brightness_end) }}
    {% endif %}


trigger:
- platform: state
  entity_id: !input output_light
  to: 'on'
- platform: time
  at: !input dim_start_time

condition:
- condition: state
  entity_id: !input output_light
  state: 'on'
- condition: or
  conditions:
    - condition: template
      value_template: "{{now_ts >= start_ts}}"
    - condition: time
      before: "06:00:00"

action:
- choose:
  - alias: "Turn on the light if necessary"
    conditions: "{{set_initial_brightness}}"
    sequence:
    - service: light.turn_on
      entity_id: !input output_light
      data:
        brightness: '{{initial_brightness | int}}'
    - delay: "00:00:01"

- delay: "00:00:01"

- service: light.turn_on
  data:
    brightness: !input end_brightness
    transition: '{{transition_time | int}}'
  entity_id: !input output_light
