esphome:
  name: cv-balkon
  comment: "Temperature sensor next to the CV ketel"

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "1e540e31e624c0b18ae0ea963953def6"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Cv-Balkon Fallback Hotspot"
    password: !secret backup_password

captive_portal:

dallas:
  - pin: 4

sensor:
  platform: dallas
  address: 0x993C01D6076A7F28
  name: "CV Temperature"
  
