homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aede9Saix6bu2Joh5eeph0aighoongaaNg6jeboo9AhxooW0ohtomie7ueGeeshe
serial:
  port: /dev/ttyACM0
frontend:
  port: 8099
devices:
  '0x001788010baa70fc':
    friendly_name: table_light_1
  '0x001788010baa7861':
    friendly_name: table_light_2
  '0x001788010b59fe29':
    friendly_name: hue light switch
  '0x90fd9ffffedfad32':
    friendly_name: hall_light
  '0x001788010ba49b00':
    friendly_name: tv_light
  '0x54ef441000714653':
    friendly_name: de_foodzi_unit
groups:
  '0':
    friendly_name: livingroom lights
    devices:
      - 0x001788010baa7861/11
      - 0x001788010baa70fc/11
      - 0x001788010ba49b00/11
advanced:
  log_level: info
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 11
availability: false
