homeassistant:
  enabled: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aede9Saix6bu2Joh5eeph0aighoongaaNg6jeboo9AhxooW0ohtomie7ueGeeshe
serial:
  port: /dev/ttyACM0
  adapter: zstack
frontend:
  enabled: true
  port: 8099
devices:
  '0x001788010baa70fc':
    friendly_name: Table Light 1
  '0x001788010baa7861':
    friendly_name: Table light 2
  '0x001788010ba49b00':
    friendly_name: TV Light
  '0x54ef441000714653':
    friendly_name: de_foodzi_unit
  '0x001788010b59fe29':
    friendly_name: hue_light_switch
  '0x000d6ffffea7e84e':
    friendly_name: Hall light 1
  '0x000d6ffffee84752':
    friendly_name: Hall Light 2
  '0x000d6ffffed9d771':
    friendly_name: Hall Light 3
groups:
  '0':
    friendly_name: Livingroom Lights
  '1':
    friendly_name: Hall Light
  '2':
    friendly_name: House Lights
  '3':
    friendly_name: Table Lights
advanced:
  log_level: warning
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 11
availability:
  enabled: false
version: 4
