homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: addons
  password: aede9Saix6bu2Joh5eeph0aighoongaaNg6jeboo9AhxooW0ohtomie7ueGeeshe
serial:
  port: /dev/ttyACM0
frontend:
  port: 8099
devices:
  '0x001788010baa7861':
    friendly_name: table light 1
    transition: 0
    availability: false
  '0x001788010baa70fc':
    friendly_name: table light 2
    transition: 0
    availability: false
  '0x001788010ba49b00':
    friendly_name: tv light
    transition: 0
    availability: false
  '0x001788010b59fe29':
    friendly_name: hue dimmer switch
    availability: false
  '0x90fd9ffffedfad32':
    friendly_name: hall light
    transition: ''
    availability: true
groups:
  '0':
    friendly_name: livingroom lights
    devices:
      - 0x001788010baa7861/11
      - 0x001788010baa70fc/11
      - 0x001788010ba49b00/11
advanced:
  log_level: info
availability: false
